### ISSUE TITLE
3.7+版本无法解析安装包

### ISSUE THREAD

**Issue by MyNameErala** [Xposed-Modules-Repo/Com.HChen.Hook#1]
API 版本
100

Xposed API 调用保护
已启用

Dex 优化器包装
不支持 (系统版本不受支持)

框架版本
1.9.2 (7049)

管理器包名
com.android.shell

系统版本
9 (API 28)

设备
Smartisan SMARTISAN OD103 

系统架构
arm64-v8a

从4.1最新版往前下载尝试安装都解析安装包失败，直到3.7版本才可以正常安装，魔趣安卓9

**Comment by HChenX** [comment]
不支持安卓9
